### ISSUE TITLE
Невозможно сделать кроссдоменный запрос (CORS)

### ISSUE THREAD

**Issue by dequubi** [jug2505/onlinevn#1]
Собственно, проблема в названии. При попытке сделать `fetch("http://localhost:8090/novel")` выдало ошибку:
```
Access to fetch at 'http://localhost:8090/novel' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Если поможет: https://qna.habr.com/q/635557

**Comment by eakuvshin** [comment]
Решено в коммите https://github.com/jug2505/onlinevn/commit/a2496d5cfd0885d986b93cc3359aa992d26a7be1

**Comment by dequubi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Возможность сделать кроссдоменный запрос](https://trello.com/c/OhBn6kdz/41-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%BA%D1%80%D0%BE%D1%81%D1%81%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81)
